name: Commit Calender
on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.MY_SECRET_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
         filename: metrics.plugin.isocalendar.fullyear.svg
         token: ${{ secrets.MY_SECRET_TOKEN }}
         base: ""
         plugin_isocalendar: yes
         plugin_isocalendar_duration: full-year
